class Events:
    UE_INITIALIZATION = 0
    UE_GENERATE_PDU_SESSION = 1
    UE_SEND_PDU_REQUEST = 2
    COMPUTE_NODE_ALLOCATE_UPF = 3
    UPF_PROCESS_PDU = 4
    PDU_SESSION_TERMINATE = 5
    UPF_TERMINATE = 6
